version: "3.3"
services:
  postgres:
    image: postgres:11.5-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - django
    ports:
      - "5432:5432"

  django:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ENVIRONMENT: ${ENVIRONMENT}
    command: sh -c "sleep 5 && python manage.py runserver 0.0.0.0:8000"
    stdin_open: true
    tty: true
    depends_on:
      - postgres
    volumes:
      - .:/app
    networks:
      - django
    ports:
      - "8000:8000"


networks:
  django:
    driver: bridge

volumes:
  pgdata: {}
